name: Griffin Working
description: Portfolio 
meta_description: "Griffin Working Portfolio"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://griffinworking.me'
gems: [jekyll-paginate]
